#!/bin/bash
# MoAI Statusline Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai statusline command.
# Paths are configured during project initialization.

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Load GLM environment variables if configured (for Agent Teams tmux mode)
if [ -f "$CLAUDE_PROJECT_DIR/.moai/.env.glm" ]; then
	# shellcheck disable=SC1091
	source "$CLAUDE_PROJECT_DIR/.moai/.env.glm"
fi

# Try moai command in PATH first
if command -v moai &> /dev/null; then
	exec moai statusline < "$temp_file"
fi

# Try detected Go bin path from initialization
if [ -f "/Users/ZaFMMG/go/bin/moai" ]; then
	exec "/Users/ZaFMMG/go/bin/moai" statusline < "$temp_file"
fi

# Try user local bin directory
if [ -f "/Users/ZaFMMG/.local/bin/moai" ]; then
	exec "/Users/ZaFMMG/.local/bin/moai" statusline < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing statusline gracefully)
exit 0
